// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXEzfy5m0iYlgrBcr7lANDQzWaM3PPjUU',
    appId: '1:973033853199:web:fa46846e26e28e7b02ae7a',
    messagingSenderId: '973033853199',
    projectId: 'schoolhub-71a00',
    authDomain: 'schoolhub-71a00.firebaseapp.com',
    storageBucket: 'schoolhub-71a00.firebasestorage.app',
    measurementId: 'G-GSG2H3L4H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdtv7YoclQGdtLENbUeIxhS5STnY1BBdY',
    appId: '1:973033853199:android:127c55a3a6ff825f02ae7a',
    messagingSenderId: '973033853199',
    projectId: 'schoolhub-71a00',
    storageBucket: 'schoolhub-71a00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAv9_Aq6ky0c6OGL5o8gtjp_N2hvCXk_U',
    appId: '1:973033853199:ios:e00d495e5b44514302ae7a',
    messagingSenderId: '973033853199',
    projectId: 'schoolhub-71a00',
    storageBucket: 'schoolhub-71a00.firebasestorage.app',
    iosBundleId: 'com.example.trackmybus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAv9_Aq6ky0c6OGL5o8gtjp_N2hvCXk_U',
    appId: '1:973033853199:ios:e00d495e5b44514302ae7a',
    messagingSenderId: '973033853199',
    projectId: 'schoolhub-71a00',
    storageBucket: 'schoolhub-71a00.firebasestorage.app',
    iosBundleId: 'com.example.trackmybus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXEzfy5m0iYlgrBcr7lANDQzWaM3PPjUU',
    appId: '1:973033853199:web:5b2efc429295bc7102ae7a',
    messagingSenderId: '973033853199',
    projectId: 'schoolhub-71a00',
    authDomain: 'schoolhub-71a00.firebaseapp.com',
    storageBucket: 'schoolhub-71a00.firebasestorage.app',
    measurementId: 'G-0QQPGHDSZ8',
  );
}
